### ISSUE TITLE
Not compatible with Angular4

### ISSUE THREAD

**Issue by baibaomen** [areijngoudt/angular-swagger-form-field#1]
Hi Ad Reijngoudt,

I'm to use this smart solution together with your swagger-ts-generator in a serious project. Now it seems not compatible with the latest angular-cli and Angular4.
Can you please give it an update?

The compilation output as following:
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in D:/_Study/s2t/node_modules/angular-swagger-form-field/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in D:/_Study/s2t/node_modules/angular-swagger-form-field/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in D:/_Study/s2t/node_modules/angular-swagger-form-field/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in D:/_Study/s2t/node_modules/angular-swagger-form-field/node_modules/@angular/core/index.d.ts, resolving symbol SwaggerFormFieldModule in D:/_Study/s2t/node_modules/angular-swagger-form-field/src/swagger-form-field.module.ts, resolving symbol SwaggerFormFieldModule in D:/_Study/s2t/node_modules/angular-swagger-form-field/src/swagger-form-field.module.ts

Thanks,
Jack Wang

**Comment by areijngoudt** [comment]
Hi Jack,

Working on it...

Ad

2017-09-04 8:32 GMT+02:00 百宝门 <notifications@github.com>:

**Comment by areijngoudt** [comment]
fixed

2017-09-04 8:32 GMT+02:00 百宝门 <notifications@github.com>:

**Comment by baibaomen** [comment]
Thanks Ad! 

It works with a minor fix on my Windows environtment:
the fsevents package needs to be configured as optional dependency in package.json:
"optionalDependencies": {
    "fsevents": "^1.0.14"
  }
